#!/usr/bin/env sh

[ "$SETDOTS_PROMPT" -le 1 ] && NO_PROMPT='--yes'
[ "$PKG_MANAGER" = "apt" ] && sudo apt purge $NO_PROMPT --autoremove "$PKG" && return

[ "$SETDOTS_PROMPT" -le 1 ] && NO_PROMPT='--noconfirm'
[ "$PKG_MANAGER" = "pacman" ] && sudo pacman -Rns $NO_PROMPT "$PKG" && return

# brew does not prompt for confirmation before installing packages and does not seem to have options to force prompting
[ "$PKG_MANAGER" = "brew" ] && HOMEBREW_AUTOREMOVE=1 brew uninstall "$PKG" && return

