#!/usr/bin/env sh

set -e


#--- DECLARE AND EXPORT GLOBAL VARIABLES ---#
export CONFMAN_DIR="$(dirname "$(realpath "$0")")"
export CONFMAN_PROMPT="${CONFMAN_PROMPT-1}" # Set default value **if** unassigned
export CONFMAN_REPO="${CONFMAN_REPO-$CONFMAN_DIR/packages}" # Set default value **if** unassigned
export CONFMAN_DEST="${CONFMAN_DEST-$HOME}" # Set default value **if** unassigned
export CONFMAN_MGR="${CONFMAN_MGR-}"
export PKG=''
PKG_FILE=''
DEFAULT_OPERATION=1


#--- IMPORT FUNCTIONS FROM OTHER SCRIPTS ---#
. "$CONFMAN_DIR/lib/utils.sh"
. "$CONFMAN_DIR/lib/validations.sh"
. "$CONFMAN_DIR/lib/pkg_manager.sh"
. "$CONFMAN_DIR/lib/operations.sh"


#--- PARSE OPTIONS ---#
OPTIND=1 # Reset OPTIND to 1 to clear any value potentially set by previous invocations of "getopts", as a safety measure.
while getopts "vhHiIsuUrlf:m:d:p:g:" OPT; do
	case "$OPT" in
	v) print_version_exit;;
	h) print_usage_exit;;
	H) show_manpage_exit;;
	i) i=1; DEFAULT_OPERATION=;;
	I) I=1; DEFAULT_OPERATION=;;
	s) s=1; DEFAULT_OPERATION=;;
	u) u=1; DEFAULT_OPERATION=;;
	U) U=1; DEFAULT_OPERATION=;;
	r) r=1; DEFAULT_OPERATION=;;
	l) l=1; DEFAULT_OPERATION=;;
	f) PKG_FILE="$OPTARG";;
	m) CONFMAN_MGR="$OPTARG";;
	d) CONFMAN_DEST="$OPTARG";;
	p) CONFMAN_PROMPT="$OPTARG";;
	g) CONFMAN_REPO="$OPTARG";;
	?) print_exit_usage;;
	esac
done
shift $((OPTIND - 1))


#--- VALIDATE AND EXPORT VARIABLES ---#
validate_option_combinations
validate_confman_path
validate_confman_prompt
validate_confman_dest
validate_confman_repo
if [ "$DEFAULT_OPERATION" ] || [ "$i" ] || [ "$I" ] || [ "$u" ] || [ "$U" ]; then validate_pkg_manager; fi


#--- OPERATE ACCORDING TO OPTIONS ---#
# Read list of selected packages from parameters and repository
read_selected_packages "$@"

# Operate according to option(s) specified
if [ "$l" ]; then
	print_exit_selected_packages
fi

warn_about_skipped_packages

if [ "$DEFAULT_OPERATION" ] || [ "$i" ] || [ "$I" ]; then
	dispatch_operations 'install'
fi

if [ "$DEFAULT_OPERATION" ] || [ "$s" ] || [ "$I" ]; then
	dispatch_operations 'setup'
fi

if [ "$u" ] || [ "$U" ]; then
	dispatch_operations 'uninstall'
fi

if [ "$r" ] || [ "$U" ]; then
	dispatch_operations 'unset'
fi

