#!/usr/bin/env sh

set -e


#--- IMPORT FUNCTIONS FROM OTHER SCRIPTS ---#
SETDOTS_DIR="$(dirname "$(realpath "$0")")"
. "$SETDOTS_DIR/lib/utils.sh"
. "$SETDOTS_DIR/lib/validations.sh"
. "$SETDOTS_DIR/lib/pkg_manager.sh"
. "$SETDOTS_DIR/lib/operations.sh"


#--- PARSE OPTIONS ---#
DEFAULT_OPERATION=1 # Install and set up selected packages if no other option, except -f and -m, is specified
OPTIND=1 # Reset OPTIND to 1 to clear any value potentially set by previous invocations of "getopts", as a safety measure.
while getopts "vhHiIsuUrlf:m:d:p:g:" OPT; do
	case "$OPT" in
	v) v=1; print_version_exit;;
	h) h=1; print_usage_exit;;
	H) H=1; show_manpage_exit;;
	i) i=1; DEFAULT_OPERATION=;;
	I) I=1; DEFAULT_OPERATION=;;
	s) s=1; DEFAULT_OPERATION=;;
	u) u=1; DEFAULT_OPERATION=;;
	U) U=1; DEFAULT_OPERATION=;;
	r) r=1; DEFAULT_OPERATION=;;
	l) l=1; DEFAULT_OPERATION=;;
	f) f="$OPTARG";;
	m) PKG_MANAGER="$OPTARG";;
	d) PKG_CONFIG_DEST="$OPTARG";;
	p) SETDOTS_PROMPT="$OPTARG";;
	g) PKG_REPO="$OPTARG";;
	?) print_exit_usage;;
	esac
done
shift $((OPTIND - 1))
validate_option_combinations


#--- VALIDATE AND EXPORT VARIABLES ---#
validate_setdots_path
validate_setdots_prompt
validate_pkg_config_dest
validate_pkg_repo
if [ "$DEFAULT_OPERATION" ] || [ "$i" ] || [ "$I" ] || [ "$u" ] || [ "$U" ]; then validate_pkg_manager; fi
export PKG_MANAGER
export SETDOTS_DIR
export SETDOTS_PROMPT
export PKG_CONFIG_DEST
export PKG_REPO


#--- OPERATE ACCORDING TO OPTIONS ---#
# Read list of selected packages from parameters and repository
read_selected_packages "$@"

# Operate according to option(s) specified
if [ "$l" ]; then
	print_exit_selected_packages
fi

warn_about_skipped_packages

if [ "$DEFAULT_OPERATION" ] || [ "$i" ] || [ "$I" ]; then
	dispatch_operations 'install'
fi

if [ "$DEFAULT_OPERATION" ] || [ "$s" ] || [ "$I" ]; then
	dispatch_operations 'setup'
fi

if [ "$u" ] || [ "$U" ]; then
	dispatch_operations 'uninstall'
fi

if [ "$r" ] || [ "$U" ]; then
	dispatch_operations 'unset'
fi

