#!/usr/bin/env sh
set -e

# By default apk is non-interactive. See FILES or --interactive on changing this default to be interactive.
if [ "$CONFMAN_PROMPT" -gt 1 ]; then PROMPT_OPT='--interactive'; fi
apk $PROMPT_OPT add $EXTRA_OPTS "$PKG" $EXTRA_ARGS

