#!/usr/bin/env sh

# brew does not prompt for confirmation before installing packages and does not seem to have options to force prompting
if [ "$HOMEBREW_CASK" ]; then CASK_OPTS='--cask --force --zap'; fi
HOMEBREW_AUTOREMOVE=1 brew uninstall $CASK_OPTS $EXTRA_OPTS "$PKG" $EXTRA_ARGS

